name: DBT Pipeline

on:
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./profiles
  DBT_TARGET: dev

jobs:
  validate-code:
    name: Validate dbt Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Validate dbt Project
        run: dbt debug

      - name: Run Unit Tests
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: |
          dbt deps
          dbt test

      - name: Deploy to BigQuery
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: dbt run
