name: DBT Pipeline

on:
  push:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./profiles
  DBT_TARGET: dev

jobs:
  validate-code:
    name: Validate dbt Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up GCP credentials
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" > ./KeySA.json

      - name: Set up profiles.yml
        run: |
          mkdir -p ~/.dbt
          echo "TestAnalytics:
          outputs:
            dev:
              dataset: DS_Test
              job_execution_timeout_seconds: 150
              job_retries: 1
              keyfile: ./KeySA.json
              location: us-central1
              method: service-account
              priority: interactive
              project: test-analytics-engineering
              threads: 1
              type: bigquery
          target: dev" > ~/.dbt/profiles.yml

      - name: Step into Project folder
        run: cd TestAnalytics
      
      - name: Validate dbt Project
        run: dbt debug

      - name: Run Unit Tests
        run: |
          dbt deps
          dbt test

      - name: Deploy to BigQuery
        run: dbt run
